### ISSUE TITLE
arm-eabi-nm: not found (but I can find arm-none-eabi-nm)

### ISSUE THREAD

**Issue by jd-imi** [ttsiodras/checkStackUsage#3]
When I started `checkStackUsage.py` on Ubuntu 22.04, I get :
```
/bin/sh: 1: arm-eabi-nm: not found
/bin/sh: 1: arm-eabi-objdump: not found
```

The package `binutils-arm-none-eabi` contains `arm-none-eabi-nm` and `arm-none-eabi-objdump` but I can't find `arm-eabi-nm` nor `arm-eabi-objdump`.

By doing this, I don't have the messages above :
```
diff --git a/checkStackUsage.py b/checkStackUsage.py
index 4c66e6a..7581963 100755
--- a/checkStackUsage.py
+++ b/checkStackUsage.py
@@ -214,8 +214,8 @@ def ParseCmdLineArgs(cross_prefix: str) -> Tuple[
             stackUsagePattern = Matcher(
                 r'^.*save.*%sp, (-([0-9]{2}|[3-9])[0-9]{2}), %sp')
         elif arm.search(binarySignature):
-            objdump = 'arm-eabi-objdump'
-            nm = 'arm-eabi-nm'
+            objdump = 'arm-none-eabi-objdump'
+            nm = 'arm-none-eabi-nm'
             functionNamePattern = Matcher(r'^(\S+) <([a-zA-Z0-9_]+?)>:')
             callPattern = Matcher(r'^.*bl\s+\S+\s+<([a-zA-Z0-9_]+)>')
             stackUsagePattern = Matcher(
```

Is my modification relevant ?

**Comment by ttsiodras** [comment]
Well, the difference between the two toolchains is that the one with the _"none-eabi"_ prefix targets embedded systems with no OS (_bare metal, hence no application binary interface - there are no applications in a monolithic embedded image_).

This is what the main README refers to when it says: _"...Adding additional platforms is very easy - just tell the script what objdump flavor to use..."_

**Comment by jd-imi** [comment]
Sorry to bother you but what I still don't understand is where can arm-eabi-nm (or arm-eabi-gcc or other tools) be found ?

On [ARM website](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads), I can find `arm-none-eabi` and `arm-none-linux-gnueabihf` but I can't find `arm-eabi`. My search on internet has been unsuccessful.

Thank you

**Comment by ttsiodras** [comment]
No problem, Jonathan. When I wrote the script - "back in the day :-)" - I believe I was using the [Linaro tools](https://releases.linaro.org/components/toolchain/binaries/). But one can also build the cross-compilers on his own - it's not so hard.

Do keep in mind though, that the script can be used with any target - targeting bare metal or OS-specific code _(i.e.  without or with an application binary interface)_ - as long as you can provide the patterns to match the stack reservations in the disassembly of your code.
